"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, ExternalLink, Menu, ShieldCheck, Wallet, X } from "lucide-react";
import { connectWallet, contractAddress, explorerUrl, readContract, unwrap, writeContract } from "@/lib/genlayer";
import { decodeReturnedAssessmentIdFromCandidates } from "@/lib/receipt";

type Totals={assessments:number;capabilities:number;deposited:number;held:number;paid:number;refunded:number};

export default function TerminalPage(){
  const[wallet,setWallet]=useState("");const[menu,setMenu]=useState(false);const[totals,setTotals]=useState<Totals|null>(null);const[notice,setNotice]=useState("Ready for a deployed contract.");const[busy,setBusy]=useState(false);
  const[asset,setAsset]=useState("DEMOUSD");const[epoch,setEpoch]=useState("20260831");const[bond,setBond]=useState("0.01");const[primary,setPrimary]=useState("");const[fallback,setFallback]=useState("");const[immutableId,setImmutableId]=useState("");const[issuerDigest,setIssuerDigest]=useState("sha256:");const[issuerByteLength,setIssuerByteLength]=useState("");const[issuerAddress,setIssuerAddress]=useState("");const[issuerAuthority,setIssuerAuthority]=useState("CANONICAL");
  const[assessmentId,setAssessmentId]=useState("");const[verifiedAssessmentId,setVerifiedAssessmentId]=useState<number|null>(null);const[counterPrimary,setCounterPrimary]=useState("");const[counterFallback,setCounterFallback]=useState("");const[counterId,setCounterId]=useState("");const[counterDigest,setCounterDigest]=useState("sha256:");const[counterByteLength,setCounterByteLength]=useState("");const[counterAuthority,setCounterAuthority]=useState("INDEPENDENT");const[consumer,setConsumer]=useState("");const[capabilityId,setCapabilityId]=useState("0");
  async function sync(){const r=await readContract("get_totals");if(r.success){const v=unwrap<Totals>(r.data);if(v)setTotals(v);setNotice("On-chain state synchronized.");}else setNotice(r.error||"Sync unavailable.");}
  async function connect(){const r=await connectWallet();if(r.success)setWallet(String(r.data));else setNotice(r.error||"Wallet connection failed.");}
  const bondWei=()=>BigInt(Math.round(Number(bond)*1e6))*BigInt(10**12);
  const validEpoch=()=>Number.isSafeInteger(Number(epoch))&&Number(epoch)>0;
  const validUrl=(value:string,id:string)=>value.startsWith("https://")&&value.includes(id)&&!value.includes("@")&&!value.toLowerCase().includes("localhost")&&!value.includes("127.0.0.1");
  const validDigest=(value:string)=>/^sha256:[0-9a-fA-F]{64}$/.test(value)&&!value.endsWith("0".repeat(64));
  const validLength=(value:string)=>Number.isSafeInteger(Number(value))&&Number(value)>0&&Number(value)<=10000;
  async function openAssessment(){if(!validEpoch()){setNotice("Assessment epoch must be a positive integer.");return;}if(!primary||!fallback||!immutableId||!validUrl(primary,immutableId)||!validUrl(fallback,immutableId)){setNotice("Add an immutable ID and two valid independent HTTPS gateways without user-info (@).");return;}setAssessmentId("");setVerifiedAssessmentId(null);setBusy(true);const r=await writeContract("open_assessment",[asset,Number(epoch),primary,fallback,immutableId,Math.floor(Date.now()/1000)+3600],bondWei());if(!r.success){setNotice(r.error||"Transaction failed.");setBusy(false);return;}try{const createdId=decodeReturnedAssessmentIdFromCandidates(r.transaction,r.receipt);const state=await readContract("get_assessment",[createdId]);if(!state.success||String(state.data)==="ASSESSMENT_NOT_FOUND")throw new Error("Authoritative assessment read-back failed");setAssessmentId(String(createdId));setVerifiedAssessmentId(createdId);setNotice(`Assessment ${createdId} opened and verified: ${r.hash}`);await sync();}catch(error){setNotice(error instanceof Error?`${error.message}. Verify ${r.hash} before continuing.`:"Assessment identity verification failed.");}finally{setBusy(false);}}
  async function loadAssessment(){const requested=Number(assessmentId);if(!Number.isSafeInteger(requested)||requested<0){setVerifiedAssessmentId(null);setNotice("Enter a valid assessment ID.");return;}const state=await readContract("get_assessment",[requested]);if(!state.success||String(state.data)==="ASSESSMENT_NOT_FOUND"){setVerifiedAssessmentId(null);setNotice(state.error||"Assessment was not found on-chain.");return;}setVerifiedAssessmentId(requested);setNotice(`Assessment ${requested} verified by authoritative read-back.`);}
  async function act(name:string,args:unknown[],value=BigInt(0)){setBusy(true);const r=await writeContract(name,args,value);if(!r.success){setNotice(r.error||"Contract action failed.");setBusy(false);return;}const state=verifiedAssessmentId===null?null:await readContract("get_assessment",[verifiedAssessmentId]);setNotice(`${name}: ${r.hash} · state ${state?.success?String(state.data):"awaiting sync"}`);setBusy(false);await sync();}
  return <main className="terminalPage">
    <header className="siteHeader"><Link className="brand" href="/#top"><span className="brandMark"><ShieldCheck/></span><span>ReserveCovenant</span></Link><nav className={menu?"nav open":"nav"}><Link href="/#top"><ArrowLeft/> Home</Link><Link href="/terminal">Assessment workspace</Link></nav><div className="headerActions"><a className="iconBtn" href={explorerUrl()} target="_blank" aria-label="Explorer"><ExternalLink/></a><button className="walletBtn" onClick={connect}><Wallet/>{wallet?`${wallet.slice(0,6)}…${wallet.slice(-4)}`:"Connect wallet"}</button><button className="menuBtn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
    <section className="section terminal"><Link className="backLink" href="/"><ArrowLeft/> Back to overview</Link><div className="terminalHeading"><div><div className="sectionTag">Assessment terminal</div><h1>Fund a live reserve epoch.</h1></div><button className="syncBtn" onClick={sync}>Sync contract</button></div>
        <div className="terminalGrid"><div className="formCard"><label>Asset symbol<input value={asset} onChange={e=>setAsset(e.target.value.toUpperCase())}/></label><label>Assessment epoch<input type="number" min="1" value={epoch} onChange={e=>setEpoch(e.target.value)}/></label><label>Issuer GEN bond<input type="number" step="0.001" value={bond} onChange={e=>setBond(e.target.value)}/></label><label>Immutable identifier<input placeholder="IPFS CID or commit hash" value={immutableId} onChange={e=>setImmutableId(e.target.value)}/></label><label>SHA-256 digest<input placeholder="sha256:…" value={issuerDigest} onChange={e=>setIssuerDigest(e.target.value)}/></label><label>Exact byte length<input type="number" min="1" max="10000" value={issuerByteLength} onChange={e=>setIssuerByteLength(e.target.value)}/></label><label>Primary gateway<input placeholder="https://…/{immutable-id}" value={primary} onChange={e=>setPrimary(e.target.value)}/></label><label>Fallback gateway<input placeholder="https://different-host/…/{immutable-id}" value={fallback} onChange={e=>setFallback(e.target.value)}/></label><button className="primaryBtn full" disabled={busy||!validEpoch()||!validUrl(primary,immutableId)||!validUrl(fallback,immutableId)} onClick={openAssessment}>{busy?"Waiting for consensus…":"Lock bond & open epoch"}<ArrowRight/></button></div>
        <aside className="ledger"><div className="ledgerHead"><span>Protocol ledger</span><span className={totals?"live":""}>{totals?"SYNCED":"NOT SYNCED"}</span></div>{[["Assessments",totals?.assessments??"—"],["GEN held",totals?`${Number(totals.held)/1e18} GEN`:"—"],["GEN settled",totals?`${Number(totals.paid)/1e18} GEN`:"—"],["Capabilities",totals?.capabilities??"—"]].map(([k,v])=><div className="metric" key={k}><span>{k}</span><strong>{v}</strong></div>)}<div className="contractBox"><small>Active contract</small><code>{contractAddress()||"Not deployed yet"}</code><a href={explorerUrl()} target="_blank">Open Explorer <ExternalLink/></a></div><p className="notice">{notice}</p></aside></div>
      <div className="operatorCard"><div className="operatorIntro"><small>Registry authority</small><h3>Approve actors and exact evidence sources</h3><p>The deployment owner binds an issuer, authority, exact URLs, SHA-256 digest and byte length to one asset and epoch before funds can be locked.</p></div><div className="operatorFields"><label>Issuer wallet<input value={issuerAddress} onChange={e=>setIssuerAddress(e.target.value)} placeholder="0x… issuer to approve"/></label><label>Issuer evidence authority<select value={issuerAuthority} onChange={e=>setIssuerAuthority(e.target.value)}><option>CANONICAL</option><option>REGULATED</option><option>INDEPENDENT</option></select></label><label>Counter evidence authority<select value={counterAuthority} onChange={e=>setCounterAuthority(e.target.value)}><option>CANONICAL</option><option>REGULATED</option><option>INDEPENDENT</option></select></label></div><div className="actionRail"><button disabled={busy||!issuerAddress||!validEpoch()} onClick={()=>act("approve_issuer",[issuerAddress,asset])}>Approve issuer</button><button disabled={busy||!validEpoch()||!validUrl(primary,immutableId)||!validUrl(fallback,immutableId)||!validDigest(issuerDigest)||!validLength(issuerByteLength)} onClick={()=>act("approve_evidence",[asset,Number(epoch),immutableId,issuerAuthority,issuerDigest,Number(issuerByteLength),primary,fallback])}>Approve issuer evidence</button><button disabled={busy||!validEpoch()||!validUrl(counterPrimary,counterId)||!validUrl(counterFallback,counterId)||!validDigest(counterDigest)||!validLength(counterByteLength)} onClick={()=>act("approve_evidence",[asset,Number(epoch),counterId,counterAuthority,counterDigest,Number(counterByteLength),counterPrimary,counterFallback])}>Approve counter evidence</button></div></div>
      <div className="operatorCard"><div className="operatorIntro"><small>Lifecycle operator</small><h3>Continue a verified epoch</h3><p>The returned ID is selected automatically. A manually entered ID must be loaded and verified before any lifecycle write is enabled.</p></div><div className="operatorFields"><label>Assessment ID<input type="number" value={assessmentId} onChange={e=>{setAssessmentId(e.target.value);setVerifiedAssessmentId(null)}}/></label><button disabled={busy||assessmentId===""} onClick={loadAssessment}>Load & verify ID</button><label>Counter immutable ID<input value={counterId} onChange={e=>setCounterId(e.target.value)} placeholder="CID or commit hash"/></label><label>Counter SHA-256 digest<input value={counterDigest} onChange={e=>setCounterDigest(e.target.value)} placeholder="sha256:…"/></label><label>Counter byte length<input type="number" min="1" max="10000" value={counterByteLength} onChange={e=>setCounterByteLength(e.target.value)}/></label><label>Counter primary URL<input value={counterPrimary} onChange={e=>setCounterPrimary(e.target.value)} placeholder="Independent evidence URL"/></label><label>Counter fallback URL<input value={counterFallback} onChange={e=>setCounterFallback(e.target.value)} placeholder="Different gateway host"/></label><label>Capability consumer<input value={consumer} onChange={e=>setConsumer(e.target.value)} placeholder="0x… protocol adapter"/></label><label>Capability ID<input type="number" value={capabilityId} onChange={e=>setCapabilityId(e.target.value)}/></label></div><div className="actionRail"><button disabled={busy||verifiedAssessmentId===null||!validUrl(counterPrimary,counterId)||!validUrl(counterFallback,counterId)} onClick={()=>act("challenge",[verifiedAssessmentId,counterPrimary,counterFallback,counterId,Math.floor(Date.now()/1000)+7200],bondWei())}>Challenge + bond</button><button disabled={busy||verifiedAssessmentId===null} onClick={()=>act("assess",[verifiedAssessmentId])}>Run AI consensus</button><button disabled={busy||verifiedAssessmentId===null} onClick={()=>act("settle",[verifiedAssessmentId])}>Settle GEN</button><button disabled={busy||verifiedAssessmentId===null} onClick={()=>act("recover",[verifiedAssessmentId])}>Recover</button><button disabled={busy||verifiedAssessmentId===null} onClick={()=>act("issue_capability",[verifiedAssessmentId,consumer])}>Issue capability</button><button disabled={busy||verifiedAssessmentId===null} onClick={()=>act("consume_capability",[Number(capabilityId),verifiedAssessmentId])}>Consume once</button></div></div>
    </section>
  </main>;
}
