"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, ExternalLink, Menu, ShieldCheck, Wallet, X } from "lucide-react";
import { connectWallet, contractAddress, explorerUrl, readContract, unwrap, writeContract } from "@/lib/genlayer";

type Totals={assessments:number;capabilities:number;deposited:number;held:number;paid:number;refunded:number};

export default function TerminalPage(){
  const[wallet,setWallet]=useState("");const[menu,setMenu]=useState(false);const[totals,setTotals]=useState<Totals|null>(null);const[notice,setNotice]=useState("Ready for a deployed contract.");const[busy,setBusy]=useState(false);
  const[asset,setAsset]=useState("DEMOUSD");const[bond,setBond]=useState("0.01");const[primary,setPrimary]=useState("");const[fallback,setFallback]=useState("");const[immutableId,setImmutableId]=useState("");
  const[assessmentId,setAssessmentId]=useState("0");const[counterPrimary,setCounterPrimary]=useState("");const[counterFallback,setCounterFallback]=useState("");const[counterId,setCounterId]=useState("");const[consumer,setConsumer]=useState("");const[capabilityId,setCapabilityId]=useState("0");
  async function sync(){const r=await readContract("get_totals");if(r.success){const v=unwrap<Totals>(r.data);if(v)setTotals(v);setNotice("On-chain state synchronized.");}else setNotice(r.error||"Sync unavailable.");}
  async function connect(){const r=await connectWallet();if(r.success)setWallet(String(r.data));else setNotice(r.error||"Wallet connection failed.");}
  const bondWei=()=>BigInt(Math.round(Number(bond)*1e6))*BigInt(10**12);
  async function openAssessment(){if(!primary||!fallback||!immutableId){setNotice("Add an immutable ID and two independent evidence gateways.");return;}setBusy(true);const r=await writeContract("open_assessment",[asset,Date.now(),primary,fallback,immutableId,Math.floor(Date.now()/1000)+3600],bondWei());setNotice(r.success?`Assessment submitted: ${r.hash}`:r.error||"Transaction failed.");setBusy(false);if(r.success)await sync();}
  async function act(name:string,args:unknown[],value=BigInt(0)){setBusy(true);const r=await writeContract(name,args,value);if(!r.success){setNotice(r.error||"Contract action failed.");setBusy(false);return;}const state=await readContract("get_assessment",[Number(assessmentId)]);setNotice(`${name}: ${r.hash} · state ${state.success?String(state.data):"awaiting sync"}`);setBusy(false);await sync();}
  return <main className="terminalPage">
    <header className="siteHeader"><Link className="brand" href="/#top"><span className="brandMark"><ShieldCheck/></span><span>ReserveCovenant</span></Link><nav className={menu?"nav open":"nav"}><Link href="/#top"><ArrowLeft/> Home</Link><Link href="/terminal">Assessment workspace</Link></nav><div className="headerActions"><a className="iconBtn" href={explorerUrl()} target="_blank" aria-label="Explorer"><ExternalLink/></a><button className="walletBtn" onClick={connect}><Wallet/>{wallet?`${wallet.slice(0,6)}…${wallet.slice(-4)}`:"Connect wallet"}</button><button className="menuBtn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
    <section className="section terminal"><Link className="backLink" href="/"><ArrowLeft/> Back to overview</Link><div className="terminalHeading"><div><div className="sectionTag">Assessment terminal</div><h1>Fund a live reserve epoch.</h1></div><button className="syncBtn" onClick={sync}>Sync contract</button></div>
      <div className="terminalGrid"><div className="formCard"><label>Asset symbol<input value={asset} onChange={e=>setAsset(e.target.value.toUpperCase())}/></label><label>Issuer GEN bond<input type="number" step="0.001" value={bond} onChange={e=>setBond(e.target.value)}/></label><label>Immutable identifier<input placeholder="IPFS CID or commit hash" value={immutableId} onChange={e=>setImmutableId(e.target.value)}/></label><label>Primary gateway<input placeholder="https://…/{immutable-id}" value={primary} onChange={e=>setPrimary(e.target.value)}/></label><label>Fallback gateway<input placeholder="https://different-host/…/{immutable-id}" value={fallback} onChange={e=>setFallback(e.target.value)}/></label><button className="primaryBtn full" disabled={busy} onClick={openAssessment}>{busy?"Waiting for consensus…":"Lock bond & open epoch"}<ArrowRight/></button></div>
        <aside className="ledger"><div className="ledgerHead"><span>Protocol ledger</span><span className={totals?"live":""}>{totals?"SYNCED":"NOT SYNCED"}</span></div>{[["Assessments",totals?.assessments??"—"],["GEN held",totals?`${Number(totals.held)/1e18} GEN`:"—"],["GEN settled",totals?`${Number(totals.paid)/1e18} GEN`:"—"],["Capabilities",totals?.capabilities??"—"]].map(([k,v])=><div className="metric" key={k}><span>{k}</span><strong>{v}</strong></div>)}<div className="contractBox"><small>Active contract</small><code>{contractAddress()||"Not deployed yet"}</code><a href={explorerUrl()} target="_blank">Open Explorer <ExternalLink/></a></div><p className="notice">{notice}</p></aside></div>
      <div className="operatorCard"><div className="operatorIntro"><small>Lifecycle operator</small><h3>Continue an existing epoch</h3><p>Each action calls the deployed contract, waits for acceptance, then re-reads assessment state.</p></div><div className="operatorFields"><label>Assessment ID<input type="number" value={assessmentId} onChange={e=>setAssessmentId(e.target.value)}/></label><label>Counter immutable ID<input value={counterId} onChange={e=>setCounterId(e.target.value)} placeholder="CID or commit hash"/></label><label>Counter primary URL<input value={counterPrimary} onChange={e=>setCounterPrimary(e.target.value)} placeholder="Independent evidence URL"/></label><label>Counter fallback URL<input value={counterFallback} onChange={e=>setCounterFallback(e.target.value)} placeholder="Different gateway host"/></label><label>Capability consumer<input value={consumer} onChange={e=>setConsumer(e.target.value)} placeholder="0x… protocol adapter"/></label><label>Capability ID<input type="number" value={capabilityId} onChange={e=>setCapabilityId(e.target.value)}/></label></div><div className="actionRail"><button disabled={busy} onClick={()=>act("challenge",[Number(assessmentId),counterPrimary,counterFallback,counterId,Math.floor(Date.now()/1000)+7200],bondWei())}>Challenge + bond</button><button disabled={busy} onClick={()=>act("assess",[Number(assessmentId)])}>Run AI consensus</button><button disabled={busy} onClick={()=>act("settle",[Number(assessmentId)])}>Settle GEN</button><button disabled={busy} onClick={()=>act("recover",[Number(assessmentId)])}>Recover</button><button disabled={busy} onClick={()=>act("issue_capability",[Number(assessmentId),consumer])}>Issue capability</button><button disabled={busy} onClick={()=>act("consume_capability",[Number(capabilityId),Number(assessmentId)])}>Consume once</button></div></div>
    </section>
  </main>;
}
